// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkTalBK-IzLFlhGE8ldEQHAhO_XCvV8J8',
    appId: '1:382960895157:web:2198c2357485e9c5f46afc',
    messagingSenderId: '382960895157',
    projectId: 'catalogo-virtual-app',
    authDomain: 'catalogo-virtual-app.firebaseapp.com',
    storageBucket: 'catalogo-virtual-app.firebasestorage.app',
    measurementId: 'G-8EQLNRVPWL',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkTalBK-IzLFlhGE8ldEQHAhO_XCvV8J8',
    appId: '1:382960895157:web:92298dd2ad6080bef46afc',
    messagingSenderId: '382960895157',
    projectId: 'catalogo-virtual-app',
    authDomain: 'catalogo-virtual-app.firebaseapp.com',
    storageBucket: 'catalogo-virtual-app.firebasestorage.app',
    measurementId: 'G-WEHLE7NWMW',
  );
}
